name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  php:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - PHP_VERSION: 7.1
            CODE_COVERAGE: false
            COMPOSER_EXTRA_ARGS: --prefer-lowest
          - PHP_VERSION: 7.1
            CODE_COVERAGE: false
          - PHP_VERSION: 7.2
            CODE_COVERAGE: true
          - PHP_VERSION: 7.3
            CODE_COVERAGE: true
          - PHP_VERSION: 7.4
            CODE_COVERAGE: true

    steps:
      - uses: actions/checkout@v2

      - name: Cache Docker Image
        id: cache-docker-image
        uses: actions/cache@v2
        with:
          path: /tmp/docker-image.tar
          key: cache-docker-image-test:${{ matrix.PHP_VERSION }}

      - name: Load Docker Image
        if: steps.cache-docker-image.outputs.cache-hit == 'true'
        run: docker load --input /tmp/docker-image.tar

      - name: Build Docker Image
        if: steps.cache-docker-image.outputs.cache-hit != 'true'
        run: docker build -f .github/workflows/test.Dockerfile -t 'test:${{ matrix.PHP_VERSION }}' --build-arg 'PHP_VERSION=${{ matrix.PHP_VERSION }}' .

      - name: Cache Composer Cache Files
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache-files
          key: cache-composer-cache-files-${{ matrix.PHP_VERSION }}
          restore-keys: |
            cache-composer-cache-files-

      - name: Install Composer Dependencies
        run: |
          docker run --rm -u "$(id -u):$(id -g)" -v "$(pwd):/workdir" -v '/tmp/composer-cache-files:/.composer' 'test:${{ matrix.PHP_VERSION }}' composer update --no-interaction --no-progress --prefer-dist ${{ matrix.COMPOSER_EXTRA_ARGS }}

      - name: Run Unit Test
        run: |
          if [ "${{ matrix.CODE_COVERAGE }}" == "true" ]; then
            docker run --rm -u "$(id -u):$(id -g)" -v "$(pwd):/workdir" 'test:${{ matrix.PHP_VERSION }}' php -d 'zend.assertions=1' -d 'pcov.enabled=1' ./vendor/bin/phpunit --coverage-clover=.clover.xml
          else
            docker run --rm -u "$(id -u):$(id -g)" -v "$(pwd):/workdir" 'test:${{ matrix.PHP_VERSION }}' php -d 'zend.assertions=1' ./vendor/bin/phpunit
          fi

      - name: Upload Codecov Report
        uses: codecov/codecov-action@v1
        if: ${{ matrix.CODE_COVERAGE }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: .clover.xml

      - name: Export Docker Image
        if: steps.cache-docker-image.outputs.cache-hit != 'true'
        run: docker save --output /tmp/docker-image.tar 'test:${{ matrix.PHP_VERSION }}'
